services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simplebank
      MYSQL_USER: simplebank
      MYSQL_PASSWORD: simplebank123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

volumes:
  mysql-data: