services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simplebank
      MYSQL_USER: simplebank
      MYSQL_PASSWORD: simplebank123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  app:
    build: .
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: mvn spring-boot:run

volumes:
  mysql-data: