services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simplebank
      MYSQL_USER: simplebank
      MYSQL_PASSWORD: simplebank123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psimplebank123"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: